### ISSUE TITLE
can't start docker-compose

### ISSUE THREAD

**Issue by user216** [jess-sys/yeelight-mqtt#1]
```bash
Successfully tagged yeelight-mqtt_yeelight_mqtt:latest
Recreating yeelight-mqtt_yeelight_mqtt_1 ... done
Attaching to yeelight-mqtt_yeelight_mqtt_1
yeelight_mqtt_1  | Traceback (most recent call last):
yeelight_mqtt_1  |   File "//main.py", line 120, in <module>
yeelight_mqtt_1  |     client.connect(MQTT_BROKER, MQTT_PORT, 60)
yeelight_mqtt_1  |   File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
yeelight_mqtt_1  |     return self.reconnect()
yeelight_mqtt_1  |   File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
yeelight_mqtt_1  |     sock = self._create_socket_connection()
yeelight_mqtt_1  |   File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
yeelight_mqtt_1  |     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
yeelight_mqtt_1  |   File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
yeelight_mqtt_1  |     raise err
yeelight_mqtt_1  |   File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
yeelight_mqtt_1  |     sock.connect(sa)
yeelight_mqtt_1  | TimeoutError: timed out
```

any ideas why this ^ happen ?

**Comment by jess-sys** [comment]
It seems like your MQTT broker is unreachable.

You need to have a running MQTT server on the network (you can start it using docker if you want to)
